[package]
name = "gltf-helpers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.20.3"
gltf = "1.0.0"
log = "0.4.16"
ordered-float = "2.10.0"
