[package]
name = "kiss-engine-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { version = "0.12.0", features = ["spirv"] }
parking_lot = "0.12.0"
rspirv-reflect = "0.6.0"
elsa = "1.7.0"
notify = "4.0.17"
log = "0.4.16"

[features]
standalone = []